version: "3.1"

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
  api:
    container_name: lemonade-api
    image: ghcr.io/academey/lemonade-api:main
    ports:
      - 8080:8080

  web:
    container_name: lemonade-web
    image: ghcr.io/academey/lemonade-web:main
    ports:
      - 3000:3000
      
  redis_container:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis/data:/data
      - ./.docker/redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf